sudo: required
language: ruby
rvm:
  - 2.6.5
  - ruby-head

env:
  - RAILS_ENV=development RACK_ENV=development

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  apt_packages:
    - libsqlite3-dev

before_install:
  - gem update --system --no-document --quiet

install:
  - bundle install --jobs=3 --retry=3
  - BUNDLE_GEMFILE=spec/integration/rails_6.0.2.1/Gemfile bundle install --jobs=4 --retry=3

script:
  - bundle exec rspec
  - bundle exec rubocop

jobs:
  include:
    - stage: gem release
      if: tag =~ ^v
      rvm: 2.6.0
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gem: annotate
        on:
          tags: true
          repo: ctran/annotate_models
