sudo: false
language: ruby
rvm:
- 2.3.8
- 2.4.9
- 2.5.7
- 2.6.5
- ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head

before_install:
- yes | gem update --system
- gem update bundler

script:
- bundle exec rubocop && bundle exec rspec

jobs:
  include:
    - stage: gem release
      if: tag =~ ^v
      rvm: 2.6.0
      script: echo "Deploying to rubygems.org ..."   
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gem: annotate
        on:
          tags: true
          repo: ctran/annotate_models
