# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 1
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 1
  timeout: 5000
